#ifndef __CONFIG_H__
#define __CONFIG_H__

/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "libyahoo2"

/* Version number of package */
#define VERSION "0.7.7"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS  1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H

/* Define to `unsigned char' if not defined. */
#define uint8_t unsigned char

/* Define to `unsigned int' if not defined. */
#define uint32_t unsigned int

/* Define to `unsigned long long' if not defined. */
#ifndef _MSC_VER
#define uint64_t unsigned long long
#else
#define uint64_t unsigned __int64
#endif

#ifdef _MSC_VER
#if _MSC_VER >= 1400 /* VC8 (VS2005) */
#define _CRT_SECURE_NO_DEPRECATE
#define _CRT_NONSTDC_NO_DEPRECATE
#if _MSC_VER >= 1500 /* VC9 (VS2008) */
#define __STDC_WANT_SECURE_LIB__ 0
#endif
#endif
#endif

#include <winsock2.h>

#ifndef _WIN32
#define _WIN32
#endif

#ifndef socklen_t
#define socklen_t int
#endif

#ifndef ECONNREFUSED
#define ECONNREFUSED WSAECONNREFUSED
#endif

#ifndef ETIMEDOUT
#define ETIMEDOUT WSAETIMEDOUT
#endif

#ifndef ENETUNREACH
#define ENETUNREACH WSAENETUNREACH
#endif

#ifndef EINPROGRESS
#define EINPROGRESS WSAEINPROGRESS
#endif

#define read(a,b,c) recv(a,b,c,0)
#define write(a,b,c) send(a,b,c,0)
#define close(a) closesocket(a)

#define snprintf _snprintf
#define vsnprintf _vsnprintf
#define strcasecmp stricmp
#define strncasecmp strnicmp

#if _MSC_VER >= 1500 /* VC9 (VS2008) */
#undef vsnprintf
#endif

#endif /*__CONFIG_H__*/
